[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
  4-20ma/ModbusMaster@^2.0.1
  knolleary/PubSubClient@^2.8

build_flags =
  -DCORE_DEBUG_LEVEL=0

; OTA upload example after first USB flash:
; upload_protocol = espota
; upload_port = esp32-sdm230.local
